server:
  port: 9000
  servlet:
    context-path: /pet
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/pet_adoption?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: pet_adoption
      password: pet_adoption020726
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
        host: smtp.qq.com
        username: jiayouuu@foxmail.com
        password: gtuixzhdoxbvdabi
        port: 465
        properties:
            mail:
                smtp:
                    socketFactory: 
                        class: javax.net.ssl.SSLSocketFactory
        default-encoding: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
jwt:
    secret: cGV0c19vbmxpbmVfYnlfamlheW91PSpLj5wuXXofO56MDWpPK35cHZmj9ui0wtfw5am4w-TR96K2
